### ISSUE TITLE
Segmentation fault when trying to dump another ruby process.

### ISSUE THREAD

**Issue by zhongxiao37** [FooBarWidget/heap_dumper_visualizer#3]
Thanks for sharing this tool. I tried it in my local and met the following errors. Could you help take a look if I missed something? Does it require specific ruby version?

### OS
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

### Ruby
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

### Files

```ruby
#test.rb
x = 'a' * 983
loop { sleep 10 }
```

```ruby
# ptmalloc_dumper.rb
require 'ffi'

module PtmallocDumper
  extend FFI::Library
  ffi_lib './libptmallocdump.so'

  attach_function :dump_non_main_heaps, [:string, :size_t], :void
  attach_function :dump_main_heap, [:string, :size_t], :void
end

PtmallocDumper.dump_main_heap('./tmp/main_heap', ARGV[0].hex)
```

#### session 1
run `ruby test.rb`

### session 2
I run `find_main_arena.sh` and get `0000003ebc40`.
And I run `grep '/libc-2.27.so$' /proc/<PID>/maps | grep ' r-xp ' | cut -d- -f 1` for session 1 PID and get `7feee62db000`.
I sum them up and get `0x7feee66c6c40`.
I run `ruby ptmalloc_dumper.rb 0x7feee66c6c40` and get following error.

```bash
ptmalloc_dumper.rb:11: [BUG] Segmentation fault at 0x00007feee66c6ca0
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0003 p:---- s:0012 e:000011 CFUNC  :dump_main_heap
c:0002 p:0041 s:0006 e:000005 EVAL   ptmalloc_dumper.rb:11 [FINISH]
c:0001 p:0000 s:0003 E:000220 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
ptmalloc_dumper.rb:11:in `<main>'
ptmalloc_dumper.rb:11:in `dump_main_heap'

-- Machine register context ------------------------------------------------
 RIP: 0x00007fe9cd285105 RBP: 0x00007ffcf0650e50 RSP: 0x00007ffcf0650df0
 RAX: 0x00007feee66c6c40 RBX: 0x0000559c7aaa5440 RCX: 0x0000000000000000
 RDX: 0x0000000000001000 RDI: 0x000000000000001e RSI: 0x0000000000000000
  R8: 0x0000000000000001  R9: 0x0000003000000002 R10: 0x000000000000000e
 R11: 0x00007fe9d0bcca50 R12: 0x00007fe9cd28508f R13: 0x00007ffcf0650fd0
 R14: 0x00007ffcf0650fb0 R15: 0x00007ffcf0651000 EFL: 0x0000000000010206

-- C level backtrace information -------------------------------------------
/root/.rbenv/versions/2.6.5/lib/libruby.so.2.6(rb_vm_bugreport+0x769) [0x7fe9d114f469] vm_dump.c:715
/root/.rbenv/versions/2.6.5/lib/libruby.so.2.6(rb_bug_context+0xe7) [0x7fe9d0f92c07] error.c:609
/root/.rbenv/versions/2.6.5/lib/libruby.so.2.6(sigsegv+0x42) [0x7fe9d10b64a2] signal.c:998
/lib/x86_64-linux-gnu/libc.so.6(0x7fe9d0b25040) [0x7fe9d0b25040]
./libptmallocdump.so(dump_main_heap+0x76) [0x7fe9cd285105] ptmallocdump.c:189
./libptmallocdump.so(dump_main_heap) (null):0
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.so(0x7fe9cd4a441a) [0x7fe9cd4a441a]
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.so(0x7fe9cd4a3d4d) [0x7fe9cd4a3d4d]
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.so(0x7fe9cd4a3dca) [0x7fe9cd4a3dca]
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.so(rbffi_CallFunction+0xde) [0x7fe9cd49778e] Call.c:400
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.so(custom_trampoline+0x34) [0x7fe9cd49b344] MethodHandle.c:220
/root/.rbenv/versions/2.6.5/lib/libruby.so.2.6(vm_call_cfunc+0x10a) [0x7fe9d112e62a] vm_insnhelper.c:1908
/root/.rbenv/versions/2.6.5/lib/libruby.so.2.6(vm_call_method+0xe3) [0x7fe9d11419a3] vm_insnhelper.c:2400
/root/.rbenv/versions/2.6.5/lib/libruby.so.2.6(vm_exec_core+0x152) [0x7fe9d1138082] insns.def:765
/root/.rbenv/versions/2.6.5/lib/libruby.so.2.6(rb_vm_exec+0x6cf) [0x7fe9d113f05f] vm.c:1894
/root/.rbenv/versions/2.6.5/lib/libruby.so.2.6(ruby_exec_internal+0xd6) [0x7fe9d0f999a6] eval.c:262
/root/.rbenv/versions/2.6.5/lib/libruby.so.2.6(ruby_exec_node+0x1d) [0x7fe9d0f9be2d] eval.c:326
/root/.rbenv/versions/2.6.5/lib/libruby.so.2.6(ruby_run_node+0x2e) [0x7fe9d0f9fdbe] eval.c:318
/root/.rbenv/versions/2.6.5/bin/ruby(main+0x5b) [0x559c7a20095b] ./main.c:42

-- Other runtime information -----------------------------------------------

* Loaded script: ptmalloc_dumper.rb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-linux/enc/encdb.so
    5 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-linux/enc/trans/transdb.so
    6 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-linux/rbconfig.rb
    7 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/compatibility.rb
    8 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/defaults.rb
    9 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/deprecate.rb
   10 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/errors.rb
   11 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/version.rb
   12 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/requirement.rb
   13 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/platform.rb
   14 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/basic_specification.rb
   15 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/stub_specification.rb
   16 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/delegate.rb
   17 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri/rfc2396_parser.rb
   18 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri/rfc3986_parser.rb
   19 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri/common.rb
   20 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri/generic.rb
   21 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri/file.rb
   22 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri/ftp.rb
   23 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri/http.rb
   24 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri/https.rb
   25 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri/ldap.rb
   26 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri/ldaps.rb
   27 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri/mailto.rb
   28 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri.rb
   29 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/specification_policy.rb
   30 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/util/list.rb
   31 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-linux/stringio.so
   32 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/specification.rb
   33 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/exceptions.rb
   34 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/util.rb
   35 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/bundler_version_finder.rb
   36 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/dependency.rb
   37 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_gem.rb
   38 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/monitor.rb
   39 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb
   40 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_warn.rb
   41 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems.rb
   42 /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/path_support.rb
   43 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/version.rb
   44 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/core_ext/name_error.rb
   45 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/levenshtein.rb
   46 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/jaro_winkler.rb
   47 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checker.rb
   48 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   49 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   50 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb
   51 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/method_name_checker.rb
   52 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/key_error_checker.rb
   53 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/null_checker.rb
   54 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/formatters/plain_formatter.rb
   55 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean.rb
   56 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.so
   57 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/platform.rb
   58 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/data_converter.rb
   59 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/types.rb
   60 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/library.rb
   61 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/errno.rb
   62 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/abstract_memory.rb
   63 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/pointer.rb
   64 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/memorypointer.rb
   65 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/struct_layout.rb
   66 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/struct_layout_builder.rb
   67 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/struct_by_reference.rb
   68 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/struct.rb
   69 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/union.rb
   70 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/managedstruct.rb
   71 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/callback.rb
   72 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/io.rb
   73 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/autopointer.rb
   74 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/variadic.rb
   75 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/enum.rb
   76 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/version.rb
   77 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi/ffi.rb
   78 /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi.rb

* Process memory map:

559c7a200000-559c7a201000 r-xp 00000000 fe:01 5509226                    /root/.rbenv/versions/2.6.5/bin/ruby
559c7a400000-559c7a401000 r--p 00000000 fe:01 5509226                    /root/.rbenv/versions/2.6.5/bin/ruby
559c7a401000-559c7a402000 rw-p 00001000 fe:01 5509226                    /root/.rbenv/versions/2.6.5/bin/ruby
559c7a7d6000-559c7acd9000 rw-p 00000000 00:00 0                          [heap]
7fe9cb037000-7fe9cbf58000 r--s 00000000 fe:01 5531300                    /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
7fe9cbf58000-7fe9cc148000 r--s 00000000 fe:01 5392219                    /lib/x86_64-linux-gnu/libc-2.27.so
7fe9cc148000-7fe9cc880000 rw-p 00000000 00:00 0
7fe9cc880000-7fe9cd06c000 r--s 00000000 fe:01 5509266                    /root/.rbenv/versions/2.6.5/lib/libruby.so.2.6.5
7fe9cd06c000-7fe9cd083000 r-xp 00000000 fe:01 5392237                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fe9cd083000-7fe9cd282000 ---p 00017000 fe:01 5392237                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fe9cd282000-7fe9cd283000 r--p 00016000 fe:01 5392237                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fe9cd283000-7fe9cd284000 rw-p 00017000 fe:01 5392237                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fe9cd284000-7fe9cd286000 r-xp 00000000 fe:01 5506376                    /usr/src/app/libptmallocdump.so
7fe9cd286000-7fe9cd485000 ---p 00002000 fe:01 5506376                    /usr/src/app/libptmallocdump.so
7fe9cd485000-7fe9cd486000 r--p 00001000 fe:01 5506376                    /usr/src/app/libptmallocdump.so
7fe9cd486000-7fe9cd487000 rw-p 00002000 fe:01 5506376                    /usr/src/app/libptmallocdump.so
7fe9cd487000-7fe9cd4ad000 r-xp 00000000 fe:01 5506223                    /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.so
7fe9cd4ad000-7fe9cd6ac000 ---p 00026000 fe:01 5506223                    /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.so
7fe9cd6ac000-7fe9cd6ad000 r--p 00025000 fe:01 5506223                    /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.so
7fe9cd6ad000-7fe9cd6ae000 rw-p 00026000 fe:01 5506223                    /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.so
7fe9cd6ae000-7fe9cd6b7000 r-xp 00000000 fe:01 5510492                    /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-linux/stringio.so
7fe9cd6b7000-7fe9cd8b6000 ---p 00009000 fe:01 5510492                    /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-linux/stringio.so
7fe9cd8b6000-7fe9cd8b7000 r--p 00008000 fe:01 5510492                    /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-linux/stringio.so
7fe9cd8b7000-7fe9cd8b8000 rw-p 00009000 fe:01 5510492                    /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-linux/stringio.so
7fe9cd8b8000-7fe9cd8ba000 r-xp 00000000 fe:01 5510451                    /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-linux/enc/trans/transdb.so
7fe9cd8ba000-7fe9cdaba000 ---p 00002000 fe:01 5510451                    /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-linux/enc/trans/transdb.so
7fe9cdaba000-7fe9cdabb000 r--p 00002000 fe:01 5510451                    /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-linux/enc/trans/transdb.so
7fe9cdabb000-7fe9cdabc000 rw-p 00003000 fe:01 5510451                    /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-linux/enc/trans/transdb.so
7fe9cdabc000-7fe9cdabe000 r-xp 00000000 fe:01 5510408                    /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-linux/enc/encdb.so
7fe9cdabe000-7fe9cdcbd000 ---p 00002000 fe:01 5510408                    /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-linux/enc/encdb.so
7fe9cdcbd000-7fe9cdcbe000 r--p 00001000 fe:01 5510408                    /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-linux/enc/encdb.so
7fe9cdcbe000-7fe9cdcbf000 rw-p 00002000 fe:01 5510408                    /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-linux/enc/encdb.so
7fe9cdcbf000-7fe9cfcc8000 rw-p 00000000 00:00 0
7fe9cfcc8000-7fe9cfe65000 r-xp 00000000 fe:01 5392244                    /lib/x86_64-linux-gnu/libm-2.27.so
7fe9cfe65000-7fe9d0064000 ---p 0019d000 fe:01 5392244                    /lib/x86_64-linux-gnu/libm-2.27.so
7fe9d0064000-7fe9d0065000 r--p 0019c000 fe:01 5392244                    /lib/x86_64-linux-gnu/libm-2.27.so
7fe9d0065000-7fe9d0066000 rw-p 0019d000 fe:01 5392244                    /lib/x86_64-linux-gnu/libm-2.27.so
7fe9d0066000-7fe9d006f000 r-xp 00000000 fe:01 5392227                    /lib/x86_64-linux-gnu/libcrypt-2.27.so
7fe9d006f000-7fe9d026e000 ---p 00009000 fe:01 5392227                    /lib/x86_64-linux-gnu/libcrypt-2.27.so
7fe9d026e000-7fe9d026f000 r--p 00008000 fe:01 5392227                    /lib/x86_64-linux-gnu/libcrypt-2.27.so
7fe9d026f000-7fe9d0270000 rw-p 00009000 fe:01 5392227                    /lib/x86_64-linux-gnu/libcrypt-2.27.so
7fe9d0270000-7fe9d029e000 rw-p 00000000 00:00 0
7fe9d029e000-7fe9d02a1000 r-xp 00000000 fe:01 5392229                    /lib/x86_64-linux-gnu/libdl-2.27.so
7fe9d02a1000-7fe9d04a0000 ---p 00003000 fe:01 5392229                    /lib/x86_64-linux-gnu/libdl-2.27.so
7fe9d04a0000-7fe9d04a1000 r--p 00002000 fe:01 5392229                    /lib/x86_64-linux-gnu/libdl-2.27.so
7fe9d04a1000-7fe9d04a2000 rw-p 00003000 fe:01 5392229                    /lib/x86_64-linux-gnu/libdl-2.27.so
7fe9d04a2000-7fe9d04a9000 r-xp 00000000 fe:01 5392284                    /lib/x86_64-linux-gnu/librt-2.27.so
7fe9d04a9000-7fe9d06a8000 ---p 00007000 fe:01 5392284                    /lib/x86_64-linux-gnu/librt-2.27.so
7fe9d06a8000-7fe9d06a9000 r--p 00006000 fe:01 5392284                    /lib/x86_64-linux-gnu/librt-2.27.so
7fe9d06a9000-7fe9d06aa000 rw-p 00007000 fe:01 5392284                    /lib/x86_64-linux-gnu/librt-2.27.so
7fe9d06aa000-7fe9d06c4000 r-xp 00000000 fe:01 5392280                    /lib/x86_64-linux-gnu/libpthread-2.27.so
7fe9d06c4000-7fe9d08c3000 ---p 0001a000 fe:01 5392280                    /lib/x86_64-linux-gnu/libpthread-2.27.so
7fe9d08c3000-7fe9d08c4000 r--p 00019000 fe:01 5392280                    /lib/x86_64-linux-gnu/libpthread-2.27.so
7fe9d08c4000-7fe9d08c5000 rw-p 0001a000 fe:01 5392280                    /lib/x86_64-linux-gnu/libpthread-2.27.so
7fe9d08c5000-7fe9d08c9000 rw-p 00000000 00:00 0
7fe9d08c9000-7fe9d08e5000 r-xp 00000000 fe:01 5392307                    /lib/x86_64-linux-gnu/libz.so.1.2.11
7fe9d08e5000-7fe9d0ae4000 ---p 0001c000 fe:01 5392307                    /lib/x86_64-linux-gnu/libz.so.1.2.11
7fe9d0ae4000-7fe9d0ae5000 r--p 0001b000 fe:01 5392307                    /lib/x86_64-linux-gnu/libz.so.1.2.11
7fe9d0ae5000-7fe9d0ae6000 rw-p 0001c000 fe:01 5392307                    /lib/x86_64-linux-gnu/libz.so.1.2.11
7fe9d0ae6000-7fe9d0ccd000 r-xp 00000000 fe:01 5392219                    /lib/x86_64-linux-gnu/libc-2.27.so
7fe9d0ccd000-7fe9d0ecd000 ---p 001e7000 fe:01 5392219                    /lib/x86_64-linux-gnu/libc-2.27.so
7fe9d0ecd000-7fe9d0ed1000 r--p 001e7000 fe:01 5392219                    /lib/x86_64-linux-gnu/libc-2.27.so
7fe9d0ed1000-7fe9d0ed3000 rw-p 001eb000 fe:01 5392219                    /lib/x86_64-linux-gnu/libc-2.27.so
7fe9d0ed3000-7fe9d0ed7000 rw-p 00000000 00:00 0
7fe9d0ed7000-7fe9d1241000 r-xp 00000000 fe:01 5509266                    /root/.rbenv/versions/2.6.5/lib/libruby.so.2.6.5
7fe9d1241000-7fe9d1440000 ---p 0036a000 fe:01 5509266                    /root/.rbenv/versions/2.6.5/lib/libruby.so.2.6.5
7fe9d1440000-7fe9d1446000 r--p 00369000 fe:01 5509266                    /root/.rbenv/versions/2.6.5/lib/libruby.so.2.6.5
7fe9d1446000-7fe9d1449000 rw-p 0036f000 fe:01 5509266                    /root/.rbenv/versions/2.6.5/lib/libruby.so.2.6.5
7fe9d1449000-7fe9d145a000 rw-p 00000000 00:00 0
7fe9d145a000-7fe9d1483000 r-xp 00000000 fe:01 5392201                    /lib/x86_64-linux-gnu/ld-2.27.so
7fe9d14e8000-7fe9d14ee000 r--s 00000000 fe:01 5506376                    /usr/src/app/libptmallocdump.so
7fe9d14ee000-7fe9d1516000 r--s 00000000 fe:01 5509226                    /root/.rbenv/versions/2.6.5/bin/ruby
7fe9d1516000-7fe9d167d000 rw-p 00000000 00:00 0
7fe9d1680000-7fe9d1681000 r-xp 00000000 00:00 0
7fe9d1681000-7fe9d1683000 rw-p 00000000 00:00 0
7fe9d1683000-7fe9d1684000 r--p 00029000 fe:01 5392201                    /lib/x86_64-linux-gnu/ld-2.27.so
7fe9d1684000-7fe9d1685000 rw-p 0002a000 fe:01 5392201                    /lib/x86_64-linux-gnu/ld-2.27.so
7fe9d1685000-7fe9d1686000 rw-p 00000000 00:00 0
7ffcefe55000-7ffcf0654000 rw-p 00000000 00:00 0                          [stack]
7ffcf0782000-7ffcf0786000 r--p 00000000 00:00 0                          [vvar]
7ffcf0786000-7ffcf0788000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]


[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: https://www.ruby-lang.org/bugreport.html

Aborted
```

**Comment by piradata** [comment]
what was the solution?
